language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t branislavburdiliak/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true branislavburdiliak/docker-react npm run test

